### ISSUE TITLE
Doesn't work + ate all the default wallpapers

### ISSUE THREAD

**Issue by The-Warlord** [amalthomas-exe/Dynamic-Wallpapers-Linux#3]
Distro: Linuxlite
WM: Xfce4

It ate all the default backgrounds :rage: 
![image](https://user-images.githubusercontent.com/63512394/167046251-6a92a5e9-f83c-44c8-afad-0b6c4ec26a22.png)

It also doesn't even work :imp: :imp: :exploding_head: 
![image](https://user-images.githubusercontent.com/63512394/167046334-ac46795f-55c8-4920-a333-87efccc6c130.png)
![image](https://user-images.githubusercontent.com/63512394/167046404-872ebfbd-4c9b-4520-a273-2f34df5282d8.png)

scam

**Comment by amalthomas-exe** [comment]
@The-Warlord Sorry for the inconveniences.

Can u please tell me the terminal output of the following command:
`crontab -l`

**Comment by emilews** [comment]
Same here, tried the `crontab -l` and got:

`no crontab for emilews`

**Comment by amalthomas-exe** [comment]
Now this looks like a serious issue. Please wait while I fix the error.

**Comment by amalthomas-exe** [comment]
@emilews Which distro are you using ? Also the desktop environment .

**Comment by emilews** [comment]
Pop! OS with GNOME 42
![image](https://user-images.githubusercontent.com/22946665/171068227-e75c491a-9035-43f4-b9cc-b099cae8d856.png)

**Comment by amalthomas-exe** [comment]
@emilews have released v1.1 to fix this issue. Pls check if that works.
