### ISSUE TITLE
TypeError: The view function for 'setWallpaper' did not return a valid response. 

### ISSUE THREAD

**Issue by tamlinek** [amalthomas-exe/Dynamic-Wallpapers-Linux#4]
Hi there,

Using Ubuntu 22.04, when I try to set up Aurora, I get this response:

tamlinek@tamlin-desktop:~$ dwl
[pywebview] closing event is deprecated and will be removed in 4.0. Use events.closing instead
 * Serving Flask app 'main' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
127.0.0.1 - - [18/May/2022 11:04:06] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/May/2022 11:04:06] "GET /static/scripts/script.js?q=1651569142 HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:06] "GET /static/styles/style.css?q=1651569142 HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:06] "GET /static/images/aurora.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:06] "GET /static/images/beach.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:06] "GET /static/images/bitday.png HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:06] "GET /static/images/catalina.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:06] "GET /static/images/cliffs.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:06] "GET /static/images/chihuahuan.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:06] "GET /static/images/colony.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:06] "GET /static/images/desert.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:06] "GET /static/images/earth.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:06] "GET /static/images/exodus.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:06] "GET /static/images/factory.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:06] "GET /static/images/firewatch.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:06] "GET /static/images/forest.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:06] "GET /static/images/gradient.png HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/home.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/island.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/lake.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/lakeside.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/london.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/maldives.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/market.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/mojave.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/mojave_HD.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/mountains.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/moon.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/mount_fuji.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/room.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/sahara.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/seoul.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/street.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/tokyo.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/colony.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/desert.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/earth.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/exodus.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/firewatch.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/factory.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/forest.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/home.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/gradient.png HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/island.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/lake.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/london.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/lakeside.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/maldives.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/market.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/mojave.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/mojave_HD.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/moon.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/mountains.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/mount_fuji.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/room.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/sahara.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/seoul.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/street.jpg HTTP/1.1" 304 -
127.0.0.1 - - [18/May/2022 11:04:07] "GET /static/images/tokyo.jpg HTTP/1.1" 304 -
aurora
Inside ubuntu
 * Reloading configuration files for periodic command scheduler cron     [ OK ] 
[2022-05-18 11:04:10,574] ERROR in app: Exception on /setWallpaper [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'setWallpaper' did not return a valid response. The function either returned None or ended without a return statement.
127.0.0.1 - - [18/May/2022 11:04:10] "GET /setWallpaper?wallpaper=aurora HTTP/1.1" 500 -

**Comment by amalthomas-exe** [comment]
Is the wallpaper changing sucessfully?

**Comment by tamlinek** [comment]
This pop-up "Linux Dynamic Wallpapers Set wallpaper to AURORA" is the only thing that comes up, wallpapers are not changed
![Zrzut ekranu z 2022-05-18 11-19-31](https://user-images.githubusercontent.com/105781404/169005110-9f3e128d-0538-424d-9781-23b40bf6140a.png)

**Comment by amalthomas-exe** [comment]
What is the output of `crontab -l`

**Comment by tamlinek** [comment]
If I get this right - nothing.

`crontab -l` cmd returns completely no reaction, when I go to var/spool/cron/crontabs, file there shows only text after hashtags. I believe I need to set this up to record in the first place, just don't know how (yet)

**Comment by amalthomas-exe** [comment]
Can you send a screenshot of the file

**Comment by tamlinek** [comment]
![Zrzut ekranu z 2022-05-18 11-47-26](https://user-images.githubusercontent.com/105781404/169010866-500b1b4b-b80c-4e50-a6c2-09489190d0af.png)

**Comment by amalthomas-exe** [comment]
What is the output of
`gsettings set org.gnome.desktop.background picture-uri file:///usr/share/linuxDynamicWallpapers/images/aurora/0.jpg` 

Like does the wallpaper change while using this command?

**Comment by tamlinek** [comment]
No reaction, wallpaper without change
![Zrzut ekranu z 2022-05-18 11-56-30](https://user-images.githubusercontent.com/105781404/169012805-efe5bc34-43bf-4fe8-8e3d-5991593e1425.png)

And definitely 0.jpg is there and `gsettings` alone gives back list of options

**Comment by amalthomas-exe** [comment]
Please look into this thread 
https://askubuntu.com/questions/531743/the-gsettings-command-line-tool-doesnt-change-the-background

I currently don't have my laptop with me so I cannot check :)

Please check if this solves your issue.

**Comment by tamlinek** [comment]
It actually didn't change anything, `set` still doesn't make any difference - but I will follow this up on askubuntu!

**Comment by amalthomas-exe** [comment]
Maybe looks like an issue with gsetting in your system. Please report this issue to Ubuntu. Maybe they can fix it :)

**Comment by tamlinek** [comment]
Will let you know if anything changes
