### ISSUE TITLE
wallpaper does not change with time

### ISSUE THREAD

**Issue by ghost** [amalthomas-exe/Dynamic-Wallpapers-Linux#5]
The app was able to setup the wallpaper just fine but after i shutdown my pc and started it the next morning, the wallpaper was still the night version. I decided to wait around 2 hours but it did not change, it stayed the same.  
 
distro : Elementary OS

**Comment by amalthomas-exe** [comment]
Please tell me the output of the following
`echo $DESKTOP_SESSION`
`crontab -l`

**Comment by Tresillo2017** [comment]
I'm getting the same issue on arch linux 

Here is the output of the command
```
plasma
no crontab for user
```
