### ISSUE TITLE
feh WARNING: [PATH TO IMAGE] does not exist - skipping

### ISSUE THREAD

**Issue by GimmeTheSallami** [amalthomas-exe/Dynamic-Wallpapers-Linux#9]
Hello,
So I just got this and Ive been trying to figure out how to fix this, I saw the other closed tabs but they were 2 yrs ago... idk but still giving the error. The window opens but dosent apply when I click on it but it does send a notif. that it applied it, I attached the output from it below. I'm running Zorin Linux Deb Based 

`[user]@[computer_name]:~$ dwl
 * Serving Flask app 'main'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:6969
Press CTRL+C to quit
127.0.0.1 - - [29/May/2024 19:46:04] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/May/2024 19:46:04] "GET /static/styles/style.css?q=1717035717 HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:04] "GET /static/scripts/script.js?q=1717035717 HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/aurora.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/beach.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/bitday.png HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/catalina.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/chihuahuan.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/cliffs.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/colony.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/desert.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/earth.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/exodus.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/firewatch.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/factory.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/forest.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/gradient.png HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/home.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/island.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/lake.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/lakeside.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/london.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/maldives.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/market.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:05] "GET /static/images/mojave.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:06] "GET /static/images/moon.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:06] "GET /static/images/mojave_HD.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:06] "GET /static/images/mountains.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:06] "GET /static/images/mount_fuji.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:06] "GET /static/images/sahara.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:06] "GET /static/images/room.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:06] "GET /static/images/seoul.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:06] "GET /static/images/tokyo.jpg HTTP/1.1" 304 -
127.0.0.1 - - [29/May/2024 19:46:06] "GET /static/images/street.jpg HTTP/1.1" 304 -
bitday
Inside zorin
feh WARNING: usr/share/linuxDynamicWallpapers/images/aurora/19.jpg does not exist - skipping
feh: No loadable images specified.
See 'man feh' for detailed usage information
 * Reloading configuration files for periodic command scheduler cron     [ OK ] 
[2024-05-29 19:46:07,370] ERROR in app: Exception on /setWallpaper [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 902, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1174, in make_response
    raise TypeError(
TypeError: The view function for 'setWallpaper' did not return a valid response. The function either returned None or ended without a return statement.
127.0.0.1 - - [29/May/2024 19:46:07] "GET /setWallpaper?wallpaper=aurora HTTP/1.1" 500 -
`

**Comment by amalthomas-exe** [comment]
Hey @GimmeTheSallami .

First of all, sorry for the late response.

This project was last updated 2 years ago, when I was a freshman. Since then, many changes both in how these Desktop environments handle wallpapers as well my professional commitments make it difficult for me to continue working on the project on a regular basis. 

I'm open to contributions from the open source community to help maintain the repository and update it on a regular basis. 

So, for now, the best I can do is suggest you to look for other similar alternatives.

Cheers!

**Comment by GimmeTheSallami** [comment]
I actually got it to work a month ago.. need to find what I did bur yeah mb, Thanks for making this to begin with.
